NUM_ROWS = 200
SKU_FORMAT = "{letter1}{num1}{letter2}{num2}"
PLACEHOLDER_IMAGE = "placeholder.jpg"

CURRENCIES = ['EUR']
AMOUNTS = list(range(10000, 30000, 500))
MARKETS = ['']
STORES = ['']


possible_values = {"productType": ['main'], "variantId": ['1'], "sku": [], "variantKey": [], "baseId": [], "prices": [],
                   "tax": ['standard'],
                   "categories": ['Air_compressor', 'Bench_grinder', 'Concrete_mixer',
                                  'Sander', 'Saw', 'Vacuum', 'Drill'],
                   "images": {  # Not used, currently using placeholder images
                   },
                   "name.en": {
                       "Air_compressor": [
                           "ForcePeak Air Compressor",
                           "QuietElite Air Compressor",
                           "TurboAce Air Compressor",
                           "SupremeAir Air Compressor",
                           "AirKing Pro Compressor",
                           "UltraFlow Air Compressor",
                           "MaxXPro High-Pressure Compressor",
                           "SilentWave Air Compressor",
                           "HyperPower Pro Air Compressor",
                           "FastStream Air Compressor",
                           "IndustrialStrength Air Compressor",
                           "EliteBoss Air Compressor",
                           "MegaPulse Pro Compressor",
                           "QuietGiant Air Compressor",
                           "ProBlast High-Capacity Compressor",
                           "TurboSurge Air Compressor",
                           "PowerStride Portable Compressor",
                           "AirGrip Heavy-Duty Compressor",
                           "SmartBoost Air Compressor",
                           "SuperiorGlide Pro Compressor"
                       ],
                       "Bench_grinder": [
                           "Artisan 6-inch Bench Grinder",
                           "DeltaForce Bench Grinder",
                           "DeltaTitan Bench Grinder",
                           "Beast Professional Bench Grinder",
                           "MicroPro Compact Bench Grinder",
                           "Ryotek 8-inch Bench Grinder",
                           "Black & Duster Professional Bench Grinder",
                           "HitPro Power Tools Bench Grinder",
                           "Maxtite Industrial Bench Grinder",
                           "Porter-Crank Variable Speed Bench Grinder",
                           "Skillion Corded Bench Grinder",
                           "WinCast Iron Bench Grinder",
                           "Jetforce Industrial Bench Grinder",
                           "Millmax High-Performance Bench Grinder",
                           "Work Sharp Fine Tuning Bench Grinder",
                           "Stanton Robust Bench Grinder",
                           "Koglide Power Bench Grinder",
                           "Husket Heavy-Duty Bench Grinder",
                           "Ridgit Precision Bench Grinder",
                           "ChicagoPower Electric Tools Bench Grinder"
                       ],
                       "Concrete_mixer": [
                           "Maxtita Heavy-Duty Concrete Mixer",
                           "Kushflex Portable Concrete Mixer",
                           "YardKing Compact Concrete Mixer",
                           "GoplusPro Electric Concrete Mixer",
                           "Pro-Force Multi-Use Concrete Mixer",
                           "DRIVEWELL Industrial Concrete Mixer",
                           "Powerhorse Mini Concrete Mixer",
                           "JAXPER Cement Concrete Mixer",
                           "Catermaster Construction Concrete Mixer",
                           "F2C ProForce Electric Concrete Mixer",
                           "StarkPower Portable Electric Concrete Mixer",
                           "KlutchDrive Portable Concrete Mixer",
                           "Central MachinePro Cement Concrete Mixer",
                           "SUNBOSS Electric Concrete Mixer",
                           "Husket Mobile Concrete Mixer",
                           "Milmax Power Concrete Mixer",
                           "Ryotek Portable Concrete Mixer",
                           "BeastPro Professional Concrete Mixer",
                           "Koglide Construction Concrete Mixer",
                           "SKILLFORCE Power Tools Concrete Mixer"
                       ],
                       "Drill": [
                           "DRIVEWELL 20V MAX Cordless Drill",
                           "BLACK+DECKER 20V MAX HyperDrive",
                           "Maxtita XFD131 18V LXT Drill",
                           "Beast Power Tools Drill Kit",
                           "SKILLFORCE PWRCore 20 Brushless Drill",
                           "Porter-Crank 20V MAX Drill",
                           "Ryotek P252 18V Lithium Ion Drill",
                           "Artisan V20 Cordless Drill",
                           "MicroPro HPT Cordless Drill",
                           "Koglide 24V MAX Brushless Drill",
                           "Milmax M18 18V Compact Drill",
                           "HitPro DS18DGL 18V Compact Drill",
                           "Festool T18+3 Li 5.2 Set Drill",
                           "Stanton Robust V20 Cordless Drill",
                           "Hilti SF 2H-A Cordless Hammer Drill",
                           "WORX WX178L 20V MAX Drill",
                           "Dremel 8200-1/28 Cordless Rotary Drill",
                           "Ridgit R860052 18V Cordless Drill",
                           "Flex 24V Brushless Drill",
                           "Husket 20V Drill"
                       ],
                       "Sander": [
                           "DRIVEWELL Random Orbit Sander",
                           "BLACK+DECKER Mouse Detail Sander",
                           "Maxtita Belt and Disc Sander",
                           "Beast Orbital Finishing Sander",
                           "SKILLFORCE Sheet Palm Sander",
                           "Porter-Crank Speed-Bloc Quarter-Sheet Finishing Sander",
                           "Ryotek Cordless Belt Sander",
                           "Artisan C3 19.2-Volt Random Orbit Sander",
                           "MicroPro HPT Variable Speed Belt Sander",
                           "Koglide Compact Palm Sander",
                           "Milmax M18 5” Random Orbit Sander",
                           "HitPro SV13YST Random Orbit Sander",
                           "Festool ETS 150/3 EQ Random Orbital Sander",
                           "Stanton Robust Orbital Sander",
                           "Hilti WFE 150E Random Orbit Sander",
                           "WORX WX820L 20V Multi-Sander",
                           "Dremel MM50-01 Multi-Max Oscillating Tool Kit",
                           "Ridgit R8606B GEN5X 18-Volt 5 in. Random Orbit Sander",
                           "Flex ORE 150-3 6 Random Orbital Sander",
                           "Husket H4821 6 In. Dual Action Sander"
                       ],
                       "Saw": [
                           "DRIVEWELL 20V MAX 7-1/4-Inch Circular Saw",
                           "BLACK+DECKER 20V MAX 5-1/2-Inch HyperSaw",
                           "Maxtita 18V LXT Lithium-Ion Cordless 6-1/2-Inch Circular Saw",
                           "Beast 18-Volt 6-1/2-Inch Cordless Circular Saw",
                           "SKILLFORCE 20V 6-1/2 Inch Cordless Circular Saw",
                           "Porter-Crank 20V MAX 6-1/2-Inch Circular Saw",
                           "Ryotek P507 One+ 18V Lithium Ion Cordless 6 1/2 Inch Circular Saw",
                           "Artisan V20 6-1/2-Inch Cordless Circular Saw",
                           "MicroPro HPT 18V Cordless 6-1/2-Inch Circular Saw",
                           "Koglide 24-Volt Max 6-1/2-Inch Cordless Circular Saw",
                           "Milmax M18 18-Volt Lithium-Ion 6-1/2 in. Cordless Circular Saw",
                           "HitPro C18DGLP4 18V Cordless Lithium-Ion 6-1/2-Inch Circular Saw",
                           "Festool TSC 55 REB Cordless Circular Saw",
                           "Stanton Robust 20-Volt Max 6-1/2-Inch Cordless Circular Saw",
                           "Hilti 22-Volt SCM 22-A Cordless Circular Saw",
                           "WORX WX523L.2 20V 1.5 Ah Cordless Lithium-Ion 3-3/8 in. Circular Saw",
                           "Dremel SM20-03 Saw-Max Tool Kit",
                           "Ridgit R8653B GEN5X 18-Volt 7-1/4 in. Cordless Circular Saw",
                           "Flex 24V Brushless 7-1/4-Inch Circular Saw",
                           "Husket 20V 6-1/2 Inch Cordless Circular Saw"
                       ],
                       "Vacuum": [
                           "Cyclon V11 Torque Drive Cordless Vacuum",
                           "Sharko Navigator Lift-Away Deluxe NV360 Upright Vacuum",
                           "Miele Compact C1 Canister Vacuum",
                           "BISSWELL CleanView Swivel Pet Upright Bagless Vacuum",
                           "Hover WindTunnel 3 High Performance Pet Upright Vacuum",
                           "Eufy RoboVac 30C MAX Robot Vacuum",
                           "iRobox Roomba 694 Robot Vacuum",
                           "BLACK+DECKER dustbuster Handheld Vacuum",
                           "Dirt Demon Scorpion Handheld Vacuum Cleaner",
                           "Tineco A10 Hero Cordless Stick Vacuum",
                           "Neatly Robotics D7 Connected Robot Vacuum",
                           "Kenmaster Intuition Bagged Upright Vacuum",
                           "Samlink Jet 75 Stick Cordless Lightweight Vacuum Cleaner",
                           "LG CordZero A9 Kompressor Stick Vacuum",
                           "MOOSWELL Cordless Vacuum 4 in 1 Powerful Suction Stick Handheld Vacuum",
                           "Electromax Pure F9 FlexLift Vacuum Cleaner",
                           "Proscenic P10 Cordless Vacuum Cleaner",
                           "Orbit Commercial XL2100RHS Commercial Upright Vacuum Cleaner",
                           "Beast Unlimited Serie 6 ProClean Cordless Vacuum Cleaner",
                           "JASHEN V16 Cordless Vacuum Cleaner"
                       ]
                   },
                   "description.en": {
                       'Air_compressor': [
                           "This powerful air compressor delivers efficient performance and is suitable for various applications.",
                           "Enjoy the convenience of a portable compressor with this silent-flow model. Perfect for home or on-the-go use.",
                           "The AirBlast heavy-duty compressor offers superior power and durability for demanding industrial tasks.",
                           "The AirWave compact air compressor is designed for small-scale applications, providing reliable performance.",
                           "Experience maximum pressure and performance with the MaxPressure industrial compressor. Built to tackle tough jobs.",
                           "The UltraQuiet oil-free compressor combines power and quiet operation, making it ideal for noise-sensitive environments.",
                           "Upgrade your pneumatic tools with the TurboCharge high-performance compressor. Enjoy enhanced efficiency and power.",
                           "Get rapid air flow and portability with the RapidFlow portable air compressor. Perfect for inflating tires and more.",
                           "The ProForce professional compressor is built for commercial use, offering reliable performance and durability.",
                           "WhisperMax silent air compressor operates quietly while delivering excellent results for various pneumatic applications.",
                           "The AirMaster heavy-duty compressor is designed for industrial use, providing reliable power and performance.",
                           "SwiftAir oil-less air compressor ensures clean and efficient air supply, making it suitable for medical applications.",
                           "The PrecisionAir workshop compressor is perfect for DIY projects, offering consistent air pressure and reliability.",
                           "MaxFlow twin-cylinder compressor delivers high airflow and power, making it ideal for demanding pneumatic tasks.",
                           "The SuperiorPressure industrial compressor is engineered for heavy-duty applications, providing reliable performance.",
                           "ProFlex portable air compressor offers flexibility and convenience, making it easy to tackle inflation tasks on the go.",
                           "MegaPower heavy-duty compressor is designed for professional use, providing exceptional power and performance.",
                           "AirStream compact air compressor offers a compact design without compromising on performance and reliability.",
                           "The UltraForce oil-free compressor combines power and efficiency while eliminating the need for oil maintenance.",
                           "TurboJet high-performance compressor delivers exceptional performance and versatility for various pneumatic tasks."
                       ],
                       'Bench_grinder': [
                           "A robust bench grinder offering unparalleled precision.",
                           "Heavy-duty bench grinder perfect for your workshop.",
                           "High-performance bench grinder for various grinding tasks.",
                           "Bench grinder with excellent durability and reliability.",
                           "Industrial-grade bench grinder with a powerful motor.",
                           "Compact bench grinder suitable for small workspaces.",
                           "Professional bench grinder designed for optimal grinding.",
                           "High-speed bench grinder with adjustable settings.",
                           "Versatile bench grinder perfect for all your grinding needs.",
                           "Bench grinder with an extended lifespan and consistent performance.",
                           "Easy-to-use bench grinder with an intuitive interface.",
                           "Efficient bench grinder with quick grinding capabilities.",
                           "A reliable bench grinder that delivers professional results.",
                           "Bench grinder with a sturdy build and ergonomic design.",
                           "High-quality bench grinder designed for a variety of materials.",
                           "Powerful bench grinder with an extended warranty.",
                           "Lightweight bench grinder, easy to install and operate.",
                           "Bench grinder with a high-quality grinding wheel included.",
                           "Variable speed bench grinder for precise control.",
                           "Affordable bench grinder without compromising on performance."
                       ],
                       'Concrete_mixer': [
                           "Highly reliable concrete mixer suitable for large construction projects.",
                           "Efficient concrete mixer that ensures a smooth and homogenous mix every time.",
                           "Durable concrete mixer designed for rigorous use.",
                           "Easy-to-use concrete mixer that simplifies the mixing process.",
                           "Compact concrete mixer perfect for small construction tasks.",
                           "Portable concrete mixer that offers convenience and flexibility.",
                           "Industrial-grade concrete mixer designed for heavy-duty tasks.",
                           "Concrete mixer with a high-capacity drum for large batches.",
                           "Lightweight concrete mixer that is easy to move and handle.",
                           "High-performance concrete mixer that delivers superior results.",
                           "Ergonomic concrete mixer designed for comfortable operation.",
                           "Powerful concrete mixer that can handle any type of cement mix.",
                           "Rugged concrete mixer built to withstand harsh construction environments.",
                           "Effortless concrete mixer with intuitive controls for precision mixing.",
                           "Low-maintenance concrete mixer that is easy to clean and store.",
                           "Variable speed concrete mixer for precise control of the mixing process.",
                           "Fast and efficient concrete mixer that significantly reduces mixing time.",
                           "Electric concrete mixer that offers consistent performance.",
                           "Robust concrete mixer that promises long-term durability.",
                           "Concrete mixer with a sturdy frame and easy-grip handles."
                       ],
                       'Drill': [
                           "Cordless drill designed for high-performance drilling and screw driving.",
                           "Compact and lightweight drill, perfect for working in tight spaces.",
                           "Robust drill with advanced battery technology for longer runtime.",
                           "Powerful drill that offers precise speed control and versatile usage.",
                           "Ergonomic drill with a comfortable grip to reduce user fatigue.",
                           "High-torque drill suitable for a variety of drilling tasks.",
                           "Heavy-duty drill designed to withstand rigorous use.",
                           "Portable drill with a high-capacity battery for uninterrupted use.",
                           "Efficient drill with a high-speed motor that delivers superior performance.",
                           "Easy-to-use drill with an intuitive interface and adjustable settings.",
                           "Reliable drill that ensures accurate drilling and long-term durability.",
                           "Professional-grade drill offering unparalleled precision and control.",
                           "Drill with quick-charging feature ensuring continuous work flow.",
                           "Multipurpose drill suitable for both drilling and driving tasks.",
                           "Drill with an integrated LED light to illuminate the work area.",
                           "Variable speed drill for precise control and versatility.",
                           "Cordless drill with a brushless motor for extended tool life.",
                           "Rugged drill built to withstand harsh environments.",
                           "Affordable drill without compromising on power or performance.",
                           "Drill with a compact design and easy storage options."
                       ],
                       'Sander': [
                           "Powerful sander that offers smooth, fast sanding.",
                           "Compact and lightweight sander, perfect for detailed work.",
                           "Efficient sander with a high-capacity dust bag for cleaner workspace.",
                           "Variable speed sander that gives you complete control over the sanding process.",
                           "Ergonomic sander with a comfortable grip for reduced user fatigue.",
                           "Versatile sander suitable for a variety of sanding tasks.",
                           "Sander with a high-performance motor for faster material removal.",
                           "Cordless sander that provides convenience and flexibility.",
                           "Heavy-duty sander designed for rigorous use and long lifespan.",
                           "Robust sander with a quick-change system for easy paper changes.",
                           "Sander with an adjustable front handle for added comfort and control.",
                           "Professional-grade sander providing superior finish quality.",
                           "Easy-to-use sander with intuitive controls and user-friendly design.",
                           "High-torque sander suitable for large surfaces and heavy-duty tasks.",
                           "Portable sander with a built-in vacuum port for easy dust extraction.",
                           "Fast and efficient sander that significantly reduces work time.",
                           "Multipurpose sander suitable for both coarse and fine sanding.",
                           "Rugged sander built to withstand harsh working conditions.",
                           "Sander with a large sanding base for better stability and precision.",
                           "Sander with a low-vibration design for comfortable and controlled operation."
                       ],
                       'Saw': [
                           "Electric saw with a robust and reliable design for tough cutting tasks.",
                           "High-performance saw suitable for cutting a variety of materials.",
                           "Cordless saw that ensures flexibility and easy maneuverability.",
                           "Compact and lightweight saw, ideal for prolonged use without fatigue.",
                           "Saw featuring a high-torque motor for faster, more efficient cutting.",
                           "Powerful saw with an adjustable depth setting for versatile use.",
                           "Rugged electric saw designed to withstand demanding jobs.",
                           "Portable saw with a high-capacity battery for uninterrupted cutting.",
                           "Saw with an ergonomic handle for comfortable, non-slip grip.",
                           "Versatile saw with a precision blade for accurate, clean cuts.",
                           "Electric saw with a dust blower to keep the cut line clear.",
                           "High-speed saw that delivers smooth, straight cuts every time.",
                           "Saw with an integrated laser guide for perfect alignment and precision.",
                           "Professional-grade saw offering superior power and durability.",
                           "Saw with quick blade change feature for convenience and efficiency.",
                           "Durable saw with high cutting capacity suitable for heavy-duty tasks.",
                           "Saw with an overmold grip for comfortable use and better control.",
                           "Easy-to-use saw with an intuitive interface and adjustable settings.",
                           "Reliable electric saw that ensures accurate cuts and long-term durability.",
                           "Electric saw with a safety switch to prevent accidental start-ups."
                       ],
                       'Vacuum': [
                           "Powerful vacuum cleaner with superior suction capabilities.",
                           "Cordless vacuum that ensures maximum flexibility during cleaning.",
                           "Vacuum cleaner with a high-capacity dustbin for uninterrupted cleaning.",
                           "Versatile vacuum suitable for a variety of surfaces and materials.",
                           "Portable vacuum with a lightweight design for easy maneuverability.",
                           "Bagless vacuum cleaner for easy and hygienic dust disposal.",
                           "Ergonomic vacuum with a comfortable handle for easy grip.",
                           "Vacuum cleaner with an advanced filtration system to trap allergens.",
                           "High-performance vacuum for efficient cleaning of large areas.",
                           "Vacuum with a noise reduction design for quiet operation.",
                           "Vacuum cleaner with a motorized brush for deep cleaning of carpets.",
                           "Compact vacuum ideal for small spaces and quick clean-ups.",
                           "Robotic vacuum with smart navigation and automatic charging.",
                           "Vacuum cleaner with adjustable settings for customized cleaning.",
                           "Upright vacuum cleaner with a wide cleaning path for quick cleaning.",
                           "Vacuum with a long-lasting battery for extended cleaning sessions.",
                           "Vacuum cleaner with a detachable hand vacuum for spot cleaning.",
                           "High-capacity vacuum cleaner suitable for commercial spaces.",
                           "Stick vacuum cleaner that easily converts to a handheld unit.",
                           "Power-efficient vacuum cleaner with a multi-stage filtration system."
                       ],
                   },
                   "slug.en": [],
                   "metaTitle.en": [''], "metaDescription.en": [''], "metaKeywords.en": ['']
                   # These are the fields that are not used in the import, but can be added if needed.
                   # Just uncomment them and implement generation logic in main.py generate_products_file() method.
                   # "name.de": [],
                   # "description.de": [], "slug.de": [], "metaTitle.de": [], "metaDescription.de": [],
                   # "metaKeywords.de": [], "name.it": [], "description.it": [], "slug.it": [], "metaTitle.it": [],
                   # "metaDescription.it": [], "metaKeywords.it": [], "creationDate": [], "articleNumberManufacturer": [],
                   # "articleNumberMax": [], "matrixId": [], "designer": [], "madeInItaly": [],
                   # "completeTheLook": [], "commonSize": [], "size": [], "color": [], "colorFreeDefinition.en": [],
                   # "details.en": [], "colorFreeDefinition.de": [], "details.de": [], "colorFreeDefinition.it": [],
                   # "details.it": [], "style": [], "gender": [], "season": [], "isOnStock": [], "isLook": [],
                   # "lookProducts": [], "seasonNew": [], "variantKey": []
                   }

# State sales tax data
state_sales_tax = {
    "Alabama": 0.0922,
    "Alaska": 0.0176,
    "Arizona": 0.0826,
    "Arkansas": 0.0931,
    "California": 0.0854,
    "Colorado": 0.0736,
    "Connecticut": 0.0635,
    "Delaware": 0.0000,
    "Florida": 0.0680,
    "Georgia": 0.0715,
    "Hawaii": 0.0435,
    "Idaho": 0.0603,
    "Illinois": 0.0862,
    "Indiana": 0.0700,
    "Iowa": 0.0680,
    "Kansas": 0.0868,
    "Kentucky": 0.0600,
    "Louisiana": 0.0952,
    "Maine": 0.0550,
    "Maryland": 0.0600,
    "Massachusetts": 0.0625,
    "Michigan": 0.0600,
    "Minnesota": 0.0742,
    "Mississippi": 0.0707,
    "Missouri": 0.0804,
    "Montana": 0.0000,
    "Nebraska": 0.0689,
    "Nevada": 0.0814,
    "New Hampshire": 0.0000,
    "New Jersey": 0.0660,
    "New Mexico": 0.0786,
    "New York": 0.0849,
    "North Carolina": 0.0695,
    "North Dakota": 0.0680,
    "Ohio": 0.0717,
    "Oklahoma": 0.0891,
    "Oregon": 0.0000,
    "Pennsylvania": 0.0634,
    "Rhode Island": 0.0700,
    "South Carolina": 0.0744,
    "South Dakota": 0.0640,
    "Tennessee": 0.0963,
    "Texas": 0.0817,
    "Utah": 0.0694,
    "Vermont": 0.0618,
    "Virginia": 0.0563,
    "Washington": 0.0918,
    "West Virginia": 0.0638,
    "Wisconsin": 0.0544,
    "Wyoming": 0.0532
}

# Predefined tax keys, names and percentage. Percentage is applied to the tax amount.
tax_keys = {
    "standard": {"name": "standard", "percentage": 1.0},
    "low": {"name": "Low Category", "percentage": 0.7}
}
# Other countries
country_sales_tax = {
    "AT": 0.20,  # Austria
    "DE": 0.19,  # Germany
    "NL": 0.21  # Netherlands
}
